name = "Hugo Tech Blog Classic Theme"
license = "MIT"
licenselink = "https://github.com/sivaprasadreddy/hugo-tech-blog-classic-theme/blob/main/LICENSE"
description = "A clean, responsive Hugo theme for technology blogs"
homepage = "https://github.com/sivaprasadreddy/hugo-tech-blog-classic-theme"
min_version = "0.164.0"
features = ["responsive", "blog", "syntax highlighting"]
demosite = "https://book.alxs.dev"

[author]
name = "SivaLabs"
homepage = "https://github.com/sivaprasadreddy/"